require'impatient'
require'settings'
require'plugins'
require'autocmd'
require'keymappings'

require'configs.tree'
require'configs.colorizer'
require'configs.null-ls'
require'configs.gitsigns'
require'configs.mason'
require'configs.lspconfigs'
require'configs.cmp'
require'configs.treesitter'
require'configs.blankline'
require'configs.comment'
require'configs.autopairs'
