require'settings'
require'plugins'
require'autocmd'
require'keymappings'

require'configs.tree'
require'configs.colorizer'
require'configs.null-ls'
require'configs.gitsigns'
require'configs.mason'
require'configs.lspconfigs'
