return {
  "andweeb/presence.nvim",
  config = function()
    require("presence").setup({
      auto_update = true,
      neovim_image_text = "Nvim",
      file_icons = {
        [".md"] = "",
        [".txt"] = "",
        [".py"] = "",
        [".js"] = "",
        [".ts"] = "",
        [".html"] = "",
        [".css"] = "",
        [".lua"] = "",
        [".json"] = "",
        [".vim"] = "",
        [".c"] = "",
        [".cpp"] = "",
        [".go"] = "",
        [".java"] = "",
        [".rs"] = "",
        [".kt"] = "",
        [".dart"] = "",
        [".sh"] = "",
        [".bash"] = "",
        [".fish"] = "",
        [".zsh"] = "",
        [".vimrc"] = "",
        [".env"] = "",
        [".gitignore"] = "",
        [".gitconfig"] = "",
        [".gitattributes"] = "",
        ["Dockerfile"] = "",
        ["Makefile"] = "",
        ["package.json"] = "",
        ["package-lock.json"] = "",
        ["webpack.config.js"] = "",
        ["tsconfig.json"] = "",
        ["vue.config.js"] = "﵂",
        [".vue"] = "﵂",
        ["rollup.config.js"] = "",
        ["yarn.lock"] = "",
        ["Cargo.toml"] = "",
        ["cargo.toml"] = "",
      },
    })
  end,
}
